# Generated by Django 5.0 on 2024-03-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_heading_1', models.CharField(max_length=100)),
                ('Post_description_1', models.CharField(max_length=2000)),
                ('Post_description_2', models.CharField(max_length=2000)),
                ('Post_name', models.CharField(max_length=500)),
                ('Vibhag', models.CharField(max_length=500)),
                ('pad_ka_nam', models.CharField(max_length=500)),
                ('Pad_ka_sankhya', models.CharField(max_length=500)),
                ('yogyta', models.CharField(max_length=500)),
                ('sallary', models.CharField(max_length=500)),
                ('vayu', models.CharField(max_length=500)),
                ('aveda_prakiya', models.CharField(max_length=500)),
                ('mukhya_website', models.CharField(max_length=500)),
                ('application_start_date', models.CharField(max_length=500)),
                ('application_end_date', models.CharField(max_length=500)),
                ('admit_cart_louch_date', models.CharField(max_length=100)),
                ('exam_date', models.CharField(max_length=100)),
                ('interview_date', models.CharField(max_length=100)),
                ('Post_heading_fees', models.CharField(max_length=500)),
                ('Post_description_fees', models.CharField(max_length=2000)),
                ('general', models.CharField(max_length=100)),
                ('obc', models.CharField(max_length=100)),
                ('st_sc', models.CharField(max_length=100)),
                ('Post_heading_Eligibility', models.CharField(max_length=500)),
                ('Post_description_Eligibility', models.CharField(max_length=2000)),
                ('eduction', models.CharField(max_length=500)),
                ('age_limitation', models.CharField(max_length=500)),
                ('nationalty', models.CharField(max_length=500)),
                ('experiance', models.CharField(max_length=500)),
                ('moolniwasi', models.CharField(max_length=500)),
            ],
        ),
    ]
