# Generated by Django 5.0 on 2024-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_railway_title_upsc_title_vyapam_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssc',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='ssc_url',
            field=models.URLField(default=1, help_text='Enter a valid URL', max_length=999),
            preserve_default=False,
        ),
    ]
