# Generated by Django 5.0.4 on 2024-04-23 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_post_date_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sarkari_post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sarkari_post',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-23T05:10:39'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sec_post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sec_post',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-23T05:10:39'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top_job',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top_job',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-23T05:10:39'),
            preserve_default=False,
        ),
    ]
