# Generated by Django 5.0.4 on 2024-04-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_sarkari_post_author_sarkari_post_date_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_job',
            name='Type',
        ),
    ]
