# Generated by Django 5.0 on 2024-04-16 07:42

import autoslug.fields
import ckeditor.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admitcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitcard', models.TextField(blank=True, null=True)),
                ('Exam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admitcard_url', models.URLField(help_text='Enter a valid URL', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Anskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anskey', models.TextField(blank=True, null=True)),
                ('Exam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('anskey_url', models.URLField(help_text='Enter a valid URL', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='borad_wish_post',
            fields=[
                ('Exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Breaking_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breaking', models.TextField(blank=True, null=True)),
                ('Breaking_url', models.URLField(help_text='Enter a valid URL', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='static/images/')),
                ('carousel_url', models.URLField(help_text='Enter a valid URL', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.TextField(blank=True, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_year_q_detail', models.TextField(blank=True, null=True)),
                ('year1', models.CharField(blank=True, max_length=100)),
                ('file1', models.FileField(upload_to='Old_Q/')),
                ('year2', models.CharField(blank=True, max_length=100)),
                ('file2', models.FileField(upload_to='Old_Q/')),
                ('year3', models.CharField(blank=True, max_length=100)),
                ('file3', models.FileField(upload_to='uploads/')),
                ('year4', models.CharField(blank=True, max_length=100)),
                ('file4', models.FileField(upload_to='Old_Q/')),
                ('year5', models.CharField(blank=True, max_length=100)),
                ('file5', models.FileField(upload_to='Old_Q/')),
            ],
        ),
        migrations.CreateModel(
            name='Railway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('railway', models.TextField(blank=True, null=True)),
                ('railway_url', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('result_url', models.URLField(help_text='Enter a valid URL', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Social_medias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Whatsapp', models.URLField(help_text='Enter a valid URL', max_length=999)),
                ('Telegram', models.URLField(help_text='Enter a valid URL', max_length=999)),
                ('Instagram', models.URLField(help_text='Enter a valid URL', max_length=999)),
                ('Facebook', models.URLField(help_text='Enter a valid URL', max_length=999)),
                ('Youtube', models.URLField(help_text='Enter a valid URL', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='SSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc', models.TextField(blank=True, null=True)),
                ('ssc_url', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('Exam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('syllabus_url', models.URLField(help_text='Enter a valid URL', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Tool_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('about_tool', models.TextField(blank=True, null=True)),
                ('tool_url', models.URLField(help_text='Enter a valid URL', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='UPSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upsc', models.TextField(blank=True, null=True)),
                ('upsc_url', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vyapam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vyapam', models.TextField(blank=True, null=True)),
                ('vyapam_url', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Pad_ka_sankhya',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Post_description_1',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Post_description_2',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Post_description_Eligibility',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Post_description_fees',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Post_heading_1',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Post_heading_Eligibility',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Post_heading_fees',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Post_name',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='Vibhag',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='admit_cart_louch_date',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='age_limitation',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='aveda_prakiya',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='eduction',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='experiance',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='general',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='moolniwasi',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='mukhya_website',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='nationalty',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='obc',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='pad_ka_nam',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='sallary',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='st_sc',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='vayu',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='yogyta',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='Ability',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='Admit_Cart_Issuance_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='Exam_Data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='Location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='age',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='application_process',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='citizenship',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='content1',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='date_information',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='department_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='departmental_ad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='experience',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='fee_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='main_website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='native',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='number_of_post',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='online_form',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='qualification_information',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='recruitment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='required_eligibility',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='salary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='title_eligibility',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='title_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='title_important_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='application_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='application_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='cat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sec_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content1', tinymce.models.HTMLField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.state')),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='state',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='blog.state'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Top_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content1', tinymce.models.HTMLField(blank=True)),
                ('detailed_information_section_i', models.TextField(blank=True, max_length=2000, null=True)),
                ('post_name', models.CharField(blank=True, max_length=500, null=True)),
                ('number_of_post', models.CharField(blank=True, max_length=500, null=True)),
                ('salary', models.CharField(blank=True, max_length=500, null=True)),
                ('application_end_date', models.DateField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.state')),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='post_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='General',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='Interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='Obc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='St_Sc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
