# Generated by Django 5.0 on 2024-04-16 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_admitcard_anskey_borad_wish_post_breaking_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sec_post',
            name='Exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.borad_wish_post'),
        ),
    ]
