# Generated by Django 5.0 on 2024-04-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ssc_title_alter_ssc_ssc_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('code', models.TextField()),
            ],
        ),
    ]
