# Generated by Django 5.0 on 2024-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_adsense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsense',
            name='code',
        ),
        migrations.RemoveField(
            model_name='adsense',
            name='name',
        ),
        migrations.AddField(
            model_name='adsense',
            name='bottom_ads',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='adsense',
            name='bottom_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adsense',
            name='left_ads',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='adsense',
            name='left_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adsense',
            name='right_ads',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='adsense',
            name='right_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adsense',
            name='top_ads',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='adsense',
            name='top_code',
            field=models.TextField(blank=True),
        ),
    ]
