# Generated by Django 5.0 on 2024-04-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_adsense_code_remove_adsense_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsense',
            old_name='bottom_ads',
            new_name='Horizantal_ads',
        ),
        migrations.RenameField(
            model_name='adsense',
            old_name='bottom_code',
            new_name='Horizantal_code',
        ),
        migrations.RenameField(
            model_name='adsense',
            old_name='left_ads',
            new_name='Vartical_ads',
        ),
        migrations.RenameField(
            model_name='adsense',
            old_name='left_code',
            new_name='Vartical_code',
        ),
        migrations.RemoveField(
            model_name='adsense',
            name='right_ads',
        ),
        migrations.RemoveField(
            model_name='adsense',
            name='right_code',
        ),
        migrations.RemoveField(
            model_name='adsense',
            name='top_ads',
        ),
        migrations.RemoveField(
            model_name='adsense',
            name='top_code',
        ),
    ]
