# Generated by Django 5.0 on 2024-04-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_bottom_ads_adsense_horizantal_ads_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sec_post',
            name='Exam',
        ),
    ]
