# Generated by Django 5.0 on 2024-04-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_sec_post_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='Tumnails',
            field=models.ImageField(default=1, upload_to='static/all_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sarkari_post',
            name='Tumnails',
            field=models.ImageField(default=2, upload_to='static/all_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sec_post',
            name='Tumnails',
            field=models.ImageField(default=1, upload_to='static/all_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top_job',
            name='Tumnails',
            field=models.ImageField(default=2, upload_to='static/all_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carousel',
            name='poster',
            field=models.ImageField(upload_to='static/all_images/'),
        ),
    ]
